### ISSUE TITLE
the wrong comparison operators are used when checking within tolerance

### ISSUE THREAD

**Issue by coyotebringsfire** [stevemacn/PageRank#4]
Is this piece of code is meant to check if the result is between min and max? I don't think that's what it's doing

lib/pagerank.js:106 
//if the result has changed push that result
if (min <= res >= max) result.push(res)

here's a demonstration in the node console where clearly res is between min and max, but this check returns false

```
> var min=0, res=1, max=2
undefined
> min <= res >= max
false
```

I'm can submit a PR to fix this, it changes the expected values though. Did you use a third-party implementation of PageRank to get the values that are used in the tests?

**Comment by stevemacn** [comment]
Yes this must have been a typo. I must have intended:

```
  min<=res<=max
```

If I remember correctly, I calculated the test results by hand but I may have found them online. I haven't really touched this code in a year and a half so I don't really remember (I should have made a comment about it). 

If you want to open the PR - I would be happy to accept it.

**Comment by coyotebringsfire** [comment]
this is fixed in PR6
