### ISSUE TITLE
A Polite Enquiry for some help

### ISSUE THREAD

**Issue by tomgallagher** [stevemacn/PageRank#9]
Hi

I'd like to be able to assess which are the most important pages on a website.

I have a collection of objects like this, one for each page:

`{"url":"https://mrcoles.com/blog/mrcolescom-launches-again/","links":["https://mrcoles.com/","https://mrcoles.com/search/","https://mrcoles.com/archive/","https://mrcoles.com/peter-coles/","https://mrcoles.com/blog/youtube-jump-time-rainbow-brite/","https://mrcoles.com/blog/phished-facebook-friends-may-be-sharing-your-info/","https://mrcoles.com/media/img/mrcoles-crypto-banner.png","https://mrcoles.com/feeds/latest/","https://mrcoles.com/demo/markdown-css/","https://mrcoles.com/blog/css-unminify/","https://mrcoles.com/bookmarklet/","https://mrcoles.com/blog/html5ify-your-existing-code-base/","https://mrcoles.com/facebook-graph-api-explorer/","https://mrcoles.com/piano/","https://mrcoles.com/dragondrop/","https://mrcoles.com/tetris/","https://mrcoles.com/low-res-paint/","https://mrcoles.com/favicon-creator/"]}`

And it looks like your project could help me?

Am I right? 

Thanks for your attention

Tom

**Comment by stevemacn** [comment]
Yes, @tomgallagher. This would work for your use case, but you would need to adjust your data a little bit to fit our current format. Something like the following would work: 

```code 
{
"https://mrcoles.com/blog/mrcolescom-launches-again/":[
        "https://mrcoles.com/",
        "https://mrcoles.com/search/",
        "https://mrcoles.com/archive/",
        "https://mrcoles.com/peter-coles/"
        ...
    ]
}
```  

Generally, page rank is used in cases where the number of links pointing to a node is an indicator of that node's importance. This isn't always true and so you will have to assess that for your own use case.

Good luck with your project!

**Comment by tomgallagher** [comment]
Thanks a lot for getting back.

So is the general idea that I make a JSON object for each page, with the url of the page as the key and the array of links as the value?

If I have an array of those JSON objects, `JSONObjectArray`, is it then as simple as 

```
nodes = JSONObjectArray;
linkProb = 0.85 //high numbers are more stable
tolerance = 0.0001 //sensitivity for accuracy of convergence. 

Pagerank(nodes, linkProb, tolerance, function (err, res) {
    if (err) throw new Error(err)
    
    //otherwise use the result (res)
})
```
And then how do I get the page rank score for each key? Will that be in the result?

Sorry for further questions.

**Comment by stevemacn** [comment]
Yes, @tomgallagher, you're correct. 

You have an array of the objects where each object represents the relationships (which pages point where). Then, the res object will return the ranks for each key.

**Comment by tomgallagher** [comment]
great, thanks for the help, I'll give it a test on Monday.
